# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Cerebro Loco
tagline:          ''
description:      'Blog dedicado a la seguridad informática y otras cosas Frikis.'
url:              http://cerebroloco.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Ian Brunelli
  url:            https://google.com/+IanCamporezBrunelli

paginate:         5

# Custom vars
icon:             /assets/images/logo.png
cover:            /assets/images/fondo.jpg

social:
  - icon:         youtube
    url:          https://www.youtube.com/channel/UClOsCxY39j1HBkLE0C10nHg
    desc:         Suscribirse al canal


menu:
  - title:        INICIO
    url:          /

  - title:        ACERCA DE
    url:          /about

copyright:
  author:         torres
  url:            http://cerebroloco.github.io/
  type_title:     #Some rights reserved
  type_url:       #http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
